### PR TITLE
Add Lidar top plate and mounting stand-offs

### PR DESCRIPTION
**Pull request by maksimmasalski**
Hi,
I suggest to add Lidar top plate.
Also add 70mm stand-offs same as 55mm you have. It will allow to install Lidar on Top. I assume that to mount lidar, user can use off-the-shelf metal or plastic standoffs.

### CODE REVIEW

**Comment by mxlfrbt** [comment]
Could you remove fillet in the front of the plate?
Just make 0 radius fillet instead of Coradial185. Because I’m making new v2 version of the robot, that will have a square shape.

**Comment by maksimmasalski** [comment]
Do you mean like that?
Screenshot 2024-08-14 101454

**Comment by mxlfrbt** [comment]
Yea, exactly.

**Comment by maksimmasalski** [comment]
I updated.

**Pull request merged**
